##### Beginning of file

branches:
    only:
    - develop
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"
        - R_HOME="*"

git:
    depth: 99999999

julia:
    - "1.0"
    - "1.1"

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
    fast_finish: true

notifications:
    email: false

os:
    - linux
    - osx

script:
    - set -ev
    - julia --project clean.jl
    - julia --project install.jl
    - julia --project clean.jl

##### End of file
