##### Beginning of file

branches:
    only:
    - develop
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"

git:
    depth: 99999999

julia:
    - "1.1"

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
    fast_finish: true

notifications:
    email: false

os:
    - linux
    - osx

script:
    - set -ev
    - julia --project -e 'ENV["PYTHON"]=""; ENV["R_HOME"]="*"; include("default-environment.jl"); include("install.jl")'
    - julia --project clean.jl

##### End of file
